import test from "node:test";
import { autoConfirmClassification } from "../apps/api/src/autoConfirm.ts";

/**
 * Independent held-out validation set for the ADR-021 non-LLM detector.
 *
 * This is NOT the regression floor (`test/auto-confirm-evaluation.test.ts`).
 * That file is allowed to grow and is asserted on in CI. This file exists to
 * answer a different question: how does the detector do on cases that were
 * NOT written by looking at what it currently gets wrong?
 *
 * Construction method: cases were drawn from (a) the eleven 要配慮個人情報
 * legal categories and this product's own stated extensions (mood, income,
 * sexual orientation) cited in ADR-021, phrased as natural paraphrases that
 * avoid the literal tokens in `autoConfirm.ts`'s keyword regex and exemplar
 * list where a natural paraphrase exists, and (b) plausible non-sensitive
 * field names, including deliberate "false friend" cases that share a
 * character or theme with a trigger word without being sensitive.
 *
 * Caveat on independence: this was written with full knowledge of
 * `autoConfirm.ts`'s current implementation (this is not a blind study from
 * someone who never saw the code), so it cannot claim true blindness. It is
 * still meaningfully more independent than editing the regression floor
 * after seeing which of ITS cases fail, because cases here were chosen from
 * the cited legal/product category list and realistic field-naming
 * conventions, not from the detector's own failure output.
 *
 * Rule: do not edit this file's cases to make failures pass. If the
 * detector changes and a case starts failing or passing differently, that
 * is a finding to report, not a reason to adjust the fixture. Re-run only
 * when `autoConfirm.ts` changes or when real production field data becomes
 * available to replace this file's role per ADR-021's Consequences.
 */

type Case = { key: string; label: string; description?: string; value?: string; sensitive: boolean; note: string };

export const AUTO_CONFIRM_HOLDOUT_SET: Case[] = [
  // Paraphrases of the eleven legal categories / product extensions, avoiding literal keyword-regex tokens.
  { key: "ethnic_roots", label: "民族的ルーツ", sensitive: true, note: "race, paraphrased" },
  { key: "faith_sect", label: "信仰する宗派", sensitive: true, note: "creed, paraphrased" },
  { key: "family_background", label: "生まれた家柄", sensitive: true, note: "social status, paraphrased" },
  { key: "past_major_illness", label: "過去にかかった大きな病気", sensitive: true, note: "medical history, paraphrased" },
  { key: "police_trouble", label: "警察のお世話になったこと", sensitive: true, note: "criminal record, colloquial paraphrase" },
  { key: "scary_experience", label: "怖い思いをした経験", sensitive: true, note: "crime victimization, paraphrased" },
  { key: "physical_inconvenience", label: "体の不自由さ", sensitive: true, note: "disability, paraphrased" },
  { key: "checkup_findings", label: "人間ドックでの指摘事項", sensitive: true, note: "health checkup results, paraphrased" },
  { key: "heart_state", label: "こころの調子", sensitive: true, note: "mental, paraphrased" },
  { key: "tension_swing", label: "テンションの浮き沈み", sensitive: true, note: "mood, colloquial paraphrase" },
  { key: "wallet_situation", label: "お財布事情", sensitive: true, note: "income, colloquial paraphrase" },
  { key: "romantic_target", label: "恋愛対象", sensitive: true, note: "sexual orientation, paraphrased" },
  { key: "bedtime_state", label: "就寝時の状態", sensitive: true, note: "sleep, paraphrased" },
  { key: "minor_guidance_history", label: "未成年時の指導歴", sensitive: true, note: "juvenile protective proceedings, paraphrased" },

  // Value-level PII that does not match the literal email/phone/postal regex.
  { key: "responsible_person", label: "担当者", value: "田中太郎", sensitive: true, note: "plain name string, not regex-shaped" },
  { key: "note", label: "メモ", value: "東京都渋谷区に住んでいます", sensitive: true, note: "address embedded in free text" },
  { key: "profile_note", label: "自己紹介", value: "連絡は090から始まる番号までお願いします", sensitive: true, note: "phone-like text embedded in prose" },

  // Deliberate false friends / true negatives.
  { key: "electricity_bill_amount", label: "電気代", sensitive: false, note: "false friend of energy/mood theme" },
  { key: "medication_reminder_app_name", label: "服薬リマインダーアプリ名", sensitive: false, note: "contains 薬 as substring; app name itself is not sensitive" },
  { key: "meeting_survey_count", label: "会議アンケート回答数", sensitive: false, note: "true negative" },
  { key: "diet_app_name", label: "食事管理アプリ名", sensitive: false, note: "true negative" },
  { key: "cpu_usage_percent", label: "CPU使用率", sensitive: false, note: "true negative" },
];

function metrics(results: boolean[], labels: boolean[]) {
  const tp = results.filter((result, index) => result && labels[index]).length;
  const fp = results.filter((result, index) => result && !labels[index]).length;
  const fn = results.filter((result, index) => !result && labels[index]).length;
  return { precision: tp / Math.max(1, tp + fp), recall: tp / Math.max(1, tp + fn), tp, fp, fn };
}

test("independent held-out validation reports layer and OR-gate quality (informational, not a CI gate)", async () => {
  const outputs = await Promise.all(AUTO_CONFIRM_HOLDOUT_SET.map((item) => autoConfirmClassification(item.key, item.label, item.description, item.value)));
  const labels = AUTO_CONFIRM_HOLDOUT_SET.map((item) => item.sensitive);
  const keyword = metrics(outputs.map((output) => output.layers.keyword), labels);
  const semantic = metrics(outputs.map((output) => output.layers.semantic), labels);
  const valuePii = metrics(outputs.map((output) => output.layers.valuePii), labels);
  const combined = metrics(outputs.map((output) => output.flagged), labels);
  const misses = AUTO_CONFIRM_HOLDOUT_SET
    .map((item, index) => ({ item, flagged: outputs[index].flagged }))
    .filter(({ item, flagged }) => item.sensitive !== flagged);
  console.log(JSON.stringify({
    sampleCount: AUTO_CONFIRM_HOLDOUT_SET.length,
    keyword, semantic, valuePii, combined,
    misses: misses.map(({ item, flagged }) => ({ key: item.key, label: item.label, expected: item.sensitive, got: flagged, note: item.note })),
  }, null, 2));
});
