import { randomUUID } from "node:crypto";
export const CONTEXT_CANDIDATE_SCHEMA_VERSION = "personal-context-candidate-v1" as const;
export type Sharing = "always" | "purpose_only" | "private" | "never";
export type Sensitivity = "normal" | "sensitive" | "highly_sensitive";
export type ContextValueType = "text" | "long_text" | "boolean" | "single_choice" | "multi_choice" | "number" | "date";
export type ContextTemplateField = { fieldKey: string; label: string; description?: string; valueType: ContextValueType; required: boolean; displayOrder: number; options?: Array<{ key: string; label: string }>; sharingDefault: Sharing; sensitivity: Sensitivity; reason: string };
export type PersonalContextCandidateV1 = { schemaVersion: typeof CONTEXT_CANDIDATE_SCHEMA_VERSION; id: string; sourceSystem: "metheory"; sourceHypothesisId: string; statement: string; construct: string; tendencyScope: "single_period_state" | "state_dependent" | "relatively_stable"; reviewStatus: "fits" | "does_not_fit" | "on_hold"; evidenceSummary: { supportingCount: number; contradictingCount: number; periodStartAt: string; periodEndAt: string }; caution: string[]; createdAt: string };
const secretPattern = /(api[_ -]?key|password|passphrase|secret|private[_ -]?key|authorization|bearer\s+)/i;
const keyPattern = /^[a-z][a-z0-9_]{0,63}$/;
export function newId(prefix: string) { return `${prefix}_${randomUUID().replaceAll("-", "")}`; }
export function isSecretLike(value: unknown) { return typeof value === "string" && secretPattern.test(value); }
export function validateField(field: ContextTemplateField): ContextTemplateField { if (!keyPattern.test(field.fieldKey) || !field.label.trim() || !field.reason.trim() || !Number.isInteger(field.displayOrder)) throw new Error("context_field_invalid"); if (!field.options && ["single_choice", "multi_choice"].includes(field.valueType)) throw new Error("context_field_options_required"); if (field.options && new Set(field.options.map((item) => item.key)).size !== field.options.length) throw new Error("context_field_options_invalid"); return field; }
export function validateCandidate(value: unknown): PersonalContextCandidateV1 { const item = value as Partial<PersonalContextCandidateV1>; if (!item || item.schemaVersion !== CONTEXT_CANDIDATE_SCHEMA_VERSION || item.sourceSystem !== "metheory" || !item.id || !item.sourceHypothesisId || !item.statement?.trim() || !item.construct || !["fits","does_not_fit","on_hold"].includes(String(item.reviewStatus)) || !item.evidenceSummary) throw new Error("personal_context_candidate_invalid"); return item as PersonalContextCandidateV1; }
export function eligibleForExport(value: { sharing: Sharing; sensitivity: Sensitivity; userConfirmed: boolean }) { return value.userConfirmed && value.sharing !== "private" && value.sharing !== "never" && value.sensitivity !== "highly_sensitive"; }
export function formatExport(fields: Array<{ label: string; value: unknown }>, format: "markdown" | "json" | "agents" | "chatgpt") { if (format === "json") return JSON.stringify(Object.fromEntries(fields.map((item) => [item.label, item.value])), null, 2); const lines = fields.map((item) => `- ${item.label}: ${typeof item.value === "string" ? item.value : JSON.stringify(item.value)}`); if (format === "agents") return `# User Context\n\n${lines.join("\n")}`; if (format === "chatgpt") return `Use the following user-approved context when it is relevant:\n${lines.join("\n")}`; return `# Personal Context\n\n${lines.join("\n")}`; }
