import type { IncomingMessage, ServerResponse } from "node:http";
import type { DatabaseSync } from "node:sqlite";

type GovernanceContext = { db: DatabaseSync; send: (response: ServerResponse, status: number, value: unknown) => unknown; body: (request: IncomingMessage) => Promise<Record<string, unknown>>; text: (value: unknown) => string; now: () => string; newId: (prefix: string) => string; destinationHost: (value: string) => string; validPurpose: (id: string) => boolean; audit: (action: string, summary: unknown) => void };

export async function handleGovernanceRoute(request: IncomingMessage, response: ServerResponse, url: URL, parts: string[], context: GovernanceContext): Promise<boolean> {
  const { db, send } = context;
  if (request.method === "GET" && url.pathname === "/v1/privacy/external-ai-consents") { send(response, 200, { items: db.prepare("SELECT id,scope,provider_id,destination_host,document_id,template_id,field_key,granted_at,revoked_at FROM context_external_ai_consents ORDER BY granted_at DESC").all() }); return true; }
  if (request.method === "POST" && url.pathname === "/v1/privacy/external-ai-consents") { const input = await context.body(request); const scope = context.text(input.scope); const providerId = context.text(input.providerId); const host = context.destinationHost(context.text(input.destinationHost)); const documentId = context.text(input.documentId); const templateId = context.text(input.templateId); const fieldKey = context.text(input.fieldKey); if (!providerId || !host || !["document", "field"].includes(scope) || (scope === "document" && !documentId) || (scope === "field" && (!templateId || !fieldKey))) { send(response, 400, { error: "external_ai_consent_invalid" }); return true; } const id = context.newId("external_ai_consent"), timestamp = context.now(); db.prepare("INSERT INTO context_external_ai_consents(id,scope,provider_id,destination_host,document_id,template_id,field_key,granted_at,revoked_at) VALUES(?,?,?,?,?,?,?,?,NULL) ON CONFLICT(scope,provider_id,destination_host,document_id,template_id,field_key) DO UPDATE SET granted_at=excluded.granted_at,revoked_at=NULL").run(id, scope, providerId, host, documentId, templateId, fieldKey, timestamp); context.audit("grant_external_ai_consent", { scope, providerId, destinationHost: host, documentId: documentId || undefined, templateId: templateId || undefined, fieldKey: fieldKey || undefined }); const consent = db.prepare("SELECT id FROM context_external_ai_consents WHERE scope=? AND provider_id=? AND destination_host=? AND document_id=? AND template_id=? AND field_key=?").get(scope, providerId, host, documentId, templateId, fieldKey) as any; send(response, 201, { id: consent.id, granted: true, scope, providerId, destinationHost: host }); return true; }
  if (request.method === "POST" && parts.join("/").match(/^v1\/privacy\/external-ai-consents\/[^/]+\/revoke$/)) { const result = db.prepare("UPDATE context_external_ai_consents SET revoked_at=? WHERE id=? AND revoked_at IS NULL").run(context.now(), parts[3]); send(response, result.changes ? 200 : 404, result.changes ? { revoked: true } : { error: "external_ai_consent_not_found" }); return true; }
  if (request.method === "GET" && url.pathname === "/v1/sharing-purposes") { send(response, 200, { items: db.prepare("SELECT * FROM context_sharing_purposes WHERE is_active=1 ORDER BY name").all() }); return true; }
  if (request.method === "POST" && url.pathname === "/v1/sharing-purposes") { const input = await context.body(request); const name = context.text(input.name); if (!name || name.length > 120) { send(response, 400, { error: "sharing_purpose_invalid" }); return true; } const id = context.newId("purpose"), timestamp = context.now(); db.prepare("INSERT INTO context_sharing_purposes(id,name,description,is_active,created_at,updated_at) VALUES(?,?,?,?,?,?)").run(id, name, context.text(input.description), 1, timestamp, timestamp); context.audit("create_sharing_purpose", { purposeId: id }); send(response, 201, { id, name }); return true; }
  if (request.method === "PUT" && parts[0] === "v1" && parts[1] === "sharing-purposes" && parts[2]) { const input = await context.body(request); const name = context.text(input.name); if (!name || name.length > 120) { send(response, 400, { error: "sharing_purpose_invalid" }); return true; } const result = db.prepare("UPDATE context_sharing_purposes SET name=?,description=?,updated_at=? WHERE id=? AND is_active=1").run(name, context.text(input.description), context.now(), parts[2]); if (!result.changes) { send(response, 404, { error: "sharing_purpose_not_found" }); return true; } context.audit("update_sharing_purpose", { purposeId: parts[2] }); send(response, 200, { updated: true }); return true; }
  if (request.method === "POST" && parts.join("/").match(/^v1\/sharing-purposes\/[^/]+\/archive$/)) { const result = db.prepare("UPDATE context_sharing_purposes SET is_active=0,updated_at=? WHERE id=? AND is_active=1").run(context.now(), parts[2]); if (!result.changes) { send(response, 404, { error: "sharing_purpose_not_found" }); return true; } context.audit("archive_sharing_purpose", { purposeId: parts[2] }); send(response, 200, { archived: true }); return true; }
  return false;
}
