import type { IncomingMessage, ServerResponse } from "node:http";
import type { DatabaseSync } from "node:sqlite";

export type LifecycleRouteContext = { db: DatabaseSync; send: (response: ServerResponse, status: number, value: unknown) => unknown; body: (request: IncomingMessage) => Promise<Record<string, unknown>>; text: (value: unknown) => string; now: () => string; audit: (action: string, summary: unknown) => void; provenance: (input: any) => void; decodedJson: (row: { value_json: string }) => unknown; validPurpose: (id: string) => boolean; valueRow: (entryId: string, fieldKey: string) => any; addRevision: (input: any) => { revisionId: string; changeType: string; lifecycleState: string }; newId: (prefix: string) => string; revisionSourceHash: (entryId: string) => string | null; exportPreview: (profileId: string, format: string, destination: string, options?: any) => any; isSecretLike: (value: unknown) => boolean; };

type ApplicabilityItem = { valueId: string; applicabilityCondition: string | null; validFrom: string | null; validTo: string | null };

function normalizedCondition(value: ApplicabilityItem): string | null { return value.applicabilityCondition === null ? null : value.applicabilityCondition.trim().toLowerCase(); }

export function rangesOverlap(left: ApplicabilityItem, right: ApplicabilityItem): boolean {
  const leftStart = left.validFrom ? Date.parse(left.validFrom) : Number.NEGATIVE_INFINITY;
  const leftEnd = left.validTo ? Date.parse(left.validTo) : Number.POSITIVE_INFINITY;
  const rightStart = right.validFrom ? Date.parse(right.validFrom) : Number.NEGATIVE_INFINITY;
  const rightEnd = right.validTo ? Date.parse(right.validTo) : Number.POSITIVE_INFINITY;
  return leftStart < rightEnd && rightStart < leftEnd;
}

export async function handleLifecycleRoute(request: IncomingMessage, response: ServerResponse, url: URL, parts: string[], context: LifecycleRouteContext): Promise<boolean> {
  const { db, send, body, text, now, audit, provenance, decodedJson, validPurpose, valueRow, addRevision, newId, revisionSourceHash, exportPreview, isSecretLike } = context;
  if (request.method === "GET" && url.pathname === "/v1/reconfirmations/due") { const items = (db.prepare("SELECT v.entry_id,v.field_key,v.value_json,v.reconfirm_after,f.label FROM context_values v JOIN context_entries e ON e.id=v.entry_id JOIN context_template_fields f ON f.template_id=e.template_id AND f.field_key=v.field_key WHERE e.status='active' AND v.user_confirmed=1 AND v.lifecycle_state='active' AND v.reconfirm_after IS NOT NULL AND v.reconfirm_after<=? ORDER BY v.reconfirm_after").all(now()) as any[]).map((value) => ({ ...value, value_json: decodedJson(value) })); send(response, 200, { items }); return true; }
  if (request.method === "GET" && url.pathname === "/v1/context-conflicts") { send(response, 200, { items: db.prepare("SELECT * FROM context_conflicts WHERE status='unresolved' ORDER BY created_at DESC").all() }); return true; }
  if (request.method === "GET" && parts[0] === "v1" && parts[1] === "context-entries" && parts[2] && parts[3] === "values" && parts[4] && parts[5] === "purposes") { const value = valueRow(parts[2], parts[4]); if (!value) { send(response, 404, { error: "context_value_not_found" }); return true; } send(response, 200, { items: db.prepare("SELECT p.* FROM context_sharing_purposes p JOIN context_value_purposes vp ON vp.purpose_id=p.id WHERE vp.value_id=? ORDER BY p.name").all(value.id) }); return true; }
  if (request.method === "PUT" && parts[0] === "v1" && parts[1] === "context-entries" && parts[2] && parts[3] === "values" && parts[4] && parts[5] === "purposes") { const input = await body(request); const value = valueRow(parts[2], parts[4]); const purposeIds = Array.isArray(input.purposeIds) ? [...new Set(input.purposeIds.filter((item): item is string => typeof item === "string" && validPurpose(item)))] : []; if (!value) { send(response, 404, { error: "context_value_not_found" }); return true; } db.exec("BEGIN IMMEDIATE"); try { db.prepare("DELETE FROM context_value_purposes WHERE value_id=?").run(value.id); const insert = db.prepare("INSERT INTO context_value_purposes(value_id,purpose_id,created_at) VALUES(?,?,?)"); for (const purposeId of purposeIds) insert.run(value.id, purposeId, now()); audit("set_value_sharing_purposes", { entryId: parts[2], fieldKey: parts[4], count: purposeIds.length }); db.exec("COMMIT"); } catch (error) { db.exec("ROLLBACK"); throw error; } send(response, 200, { purposeIds }); return true; }
  if (request.method === "POST" && parts[0] === "v1" && parts[1] === "context-conflicts" && parts[2] && parts[3] === "resolve") {
    const input = await body(request);
    const status = text(input.status);
    const reason = text(input.reason) || "User resolved the conflict in the management UI.";
    const conflict = db.prepare("SELECT value_ids_json FROM context_conflicts WHERE id=? AND status='unresolved'").get(parts[2]) as { value_ids_json: string } | undefined;
    if (!conflict) { send(response, 404, { error: "context_conflict_not_found" }); return true; }
    const valueIds = JSON.parse(conflict.value_ids_json) as string[];
    const placeholders = valueIds.map(() => "?").join(",");
    const values = db.prepare("SELECT * FROM context_values WHERE id IN (" + placeholders + ") AND lifecycle_state='active' ORDER BY updated_at DESC").all(...valueIds) as any[];
    const selectedValueIds = Array.isArray(input.selectedValueIds) ? [...new Set(input.selectedValueIds.filter((item): item is string => typeof item === "string"))] : [];
    const applicabilityCondition = text(input.applicabilityCondition) || null;
    const validFrom = text(input.validFrom) || null;
    const validTo = text(input.validTo) || null;
    const rawApplicabilityItems = Array.isArray(input.applicabilityItems) ? input.applicabilityItems : [];
    const applicabilityItems: ApplicabilityItem[] = rawApplicabilityItems
      .filter((item): item is Record<string, unknown> => Boolean(item) && typeof item === "object" && !Array.isArray(item))
      .map((item) => ({
        valueId: text(item.valueId),
        applicabilityCondition: text(item.applicabilityCondition) || null,
        validFrom: text(item.validFrom) || null,
        validTo: text(item.validTo) || null
      }));
    if (!values.length || values.length !== valueIds.length || reason.length > 1000 || !["keep_latest", "keep_both", "resolved_manually"].includes(status)) { send(response, 400, { error: "conflict_resolution_invalid" }); return true; }
    if (selectedValueIds.some((id) => !valueIds.includes(id))) { send(response, 400, { error: "conflict_resolution_invalid" }); return true; }
    if ((validFrom && Number.isNaN(Date.parse(validFrom))) || (validTo && Number.isNaN(Date.parse(validTo))) || (validFrom && validTo && Date.parse(validFrom) >= Date.parse(validTo))) { send(response, 400, { error: "conflict_resolution_invalid" }); return true; }
    const keptApplicabilityItems = status === "keep_both"
      ? (applicabilityItems.length ? applicabilityItems : selectedValueIds.map((valueId) => ({ valueId, applicabilityCondition, validFrom, validTo })))
      : [];
    if (status === "keep_both" && (!selectedValueIds.length || selectedValueIds.length !== values.length || keptApplicabilityItems.length !== values.length || keptApplicabilityItems.some((item) => !valueIds.includes(item.valueId) || (!item.applicabilityCondition && !item.validFrom && !item.validTo) || (item.validFrom && Number.isNaN(Date.parse(item.validFrom))) || (item.validTo && Number.isNaN(Date.parse(item.validTo))) || (item.validFrom && item.validTo && Date.parse(item.validFrom) >= Date.parse(item.validTo))) || new Set(keptApplicabilityItems.map((item) => item.valueId)).size !== values.length)) { send(response, 400, { error: "conflict_resolution_invalid" }); return true; }
    if (status === "keep_both") {
      for (let index = 0; index < keptApplicabilityItems.length; index += 1) {
        for (let other = index + 1; other < keptApplicabilityItems.length; other += 1) {
          const left = keptApplicabilityItems[index];
          const right = keptApplicabilityItems[other];
          if (left.valueId !== right.valueId && normalizedCondition(left) === normalizedCondition(right) && rangesOverlap(left, right)) { send(response, 400, { error: "context_value_applicability_overlap" }); return true; }
        }
      }
      const existing = db.prepare("SELECT value_id,applicability_condition,valid_from,valid_to FROM context_value_applicability WHERE value_id IN (" + valueIds.map(() => "?").join(",") + ")").all(...valueIds) as Array<{ value_id: string; applicability_condition: string | null; valid_from: string | null; valid_to: string | null }>;
      if (keptApplicabilityItems.some((item) => existing.some((row) => row.value_id !== item.valueId && normalizedCondition(item) === normalizedCondition({ valueId: row.value_id, applicabilityCondition: row.applicability_condition, validFrom: row.valid_from, validTo: row.valid_to }) && rangesOverlap(item, { valueId: row.value_id, applicabilityCondition: row.applicability_condition, validFrom: row.valid_from, validTo: row.valid_to })))) { send(response, 400, { error: "context_value_applicability_overlap" }); return true; }
    }
    const baseValueId = text(input.baseValueId) || selectedValueIds[0] || (status === "keep_latest" ? String(values[0].id) : "");
    if (status === "resolved_manually" && (!baseValueId || !valueIds.includes(baseValueId) || input.newValue === undefined)) { send(response, 400, { error: "conflict_resolution_invalid" }); return true; }
    const kept = status === "keep_both" ? new Set(selectedValueIds) : new Set([baseValueId]);
    db.exec("BEGIN IMMEDIATE");
    try {
      const timestamp = now(); let newRevisionId: string | null = null;
      if (status === "resolved_manually") { const selected = values.find((value) => value.id === baseValueId); if (!selected) throw new Error("conflict_resolution_invalid"); const revision = addRevision({ entryId: selected.entry_id, fieldKey: selected.field_key, value: input.newValue, changeType: "correction", reason, sharing: input.sharing, sensitivity: input.sensitivity, validFrom, validTo }); newRevisionId = revision.revisionId; }
      if (status === "keep_both") { const insertApplicability = db.prepare("INSERT INTO context_value_applicability(id,value_id,conflict_id,applicability_condition,valid_from,valid_to,created_at) VALUES(?,?,?,?,?,?,?)"); for (const item of keptApplicabilityItems) insertApplicability.run(newId("applicability"), item.valueId, parts[2], item.applicabilityCondition, item.validFrom, item.validTo, timestamp); }
      const retractedValueIds = values.filter((value) => !kept.has(String(value.id))).map((value) => String(value.id));
      const revisionInsert = db.prepare("INSERT INTO context_value_revisions(id,value_id,entry_id,field_key,value_json,change_type,reason,valid_from,valid_to,sharing,sensitivity,supersedes_revision_id,source_id,source_content_hash,user_confirmed,confirmed_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
      for (const value of values.filter((item) => retractedValueIds.includes(String(item.id)))) { const revisionId = newId("revision"); revisionInsert.run(revisionId, value.id, value.entry_id, value.field_key, value.value_json, "retraction", reason, null, null, value.sharing, value.sensitivity, value.current_revision_id ?? null, value.source_id ?? null, revisionSourceHash(value.entry_id), 1, timestamp, timestamp); db.prepare("UPDATE context_values SET lifecycle_state='retracted',current_revision_id=?,updated_at=? WHERE id=?").run(revisionId, timestamp, value.id); }
      const resolution = { reason, baseValueId: status === "resolved_manually" ? baseValueId : null, newRevisionId, newValue: status === "resolved_manually" ? input.newValue : null, sharing: status === "resolved_manually" ? text(input.sharing) || null : null, sensitivity: status === "resolved_manually" ? text(input.sensitivity) || null : null, applicabilityCondition, validFrom, validTo, applicabilityItems: keptApplicabilityItems, retractedValueIds };
      db.prepare("UPDATE context_conflicts SET status=?,resolution_json=?,resolved_at=? WHERE id=? AND status='unresolved'").run(status, JSON.stringify(resolution), timestamp, parts[2]);
      audit("resolve_context_conflict", { conflictId: parts[2], status, baseValueId, newRevisionId, retractedValueIds }); db.exec("COMMIT"); send(response, 200, { resolved: true, status, resolution });
    } catch (error) { db.exec("ROLLBACK"); throw error; }
    return true;
  }
  if (request.method === "POST" && (url.pathname === "/v1/context-exports/preview" || url.pathname === "/v1/context-exports")) { const input = await body(request); const format = text(input.format) || "markdown"; const target = text(input.target) || undefined; const destination = text(input.destination); if (destination.length > 200 || isSecretLike(destination)) { send(response, 400, { error: "export_request_invalid" }); return true; } const preview = exportPreview(text(input.profileId), format, destination, { target, maximumCharacters: input.maximumCharacters, maximumTokens: input.maximumTokens }); if (url.pathname.endsWith("preview")) { send(response, 200, preview); return true; } if (!text(input.previewFingerprint) || text(input.previewFingerprint) !== preview.previewFingerprint) { send(response, 409, { error: "export_preview_stale" }); return true; } const id = newId("export"); const manifest = { schemaVersion: preview.schemaVersion, includedCount: preview.includedCount, omitted: preview.omitted, destination, target: preview.target, previewFingerprint: preview.previewFingerprint, maximumCharacters: preview.maximumCharacters, maximumTokens: preview.maximumTokens }; db.prepare("INSERT INTO context_exports(id,profile_id,purpose_id,destination,format,target,preview_fingerprint,maximum_tokens,renderer_version,detail_level,content,manifest_json,omitted_count,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(id, preview.profile.id, preview.profile.purpose_id ?? null, destination, preview.format, preview.target, preview.previewFingerprint, preview.maximumTokens, preview.rendererVersion, preview.detailLevel, preview.content, JSON.stringify(manifest), preview.omittedCount, now()); audit("export_context", { exportId: id, format: preview.format, target: preview.target, destination, omittedCount: preview.omittedCount }); provenance({ subjectType: "export", subjectId: id, eventType: "created", actorType: "user", sourceRef: preview.profile.id, payload: manifest }); send(response, 201, { id, ...preview }); return true; }
  if (request.method === "GET" && url.pathname === "/v1/context-exports") { send(response, 200, { items: db.prepare("SELECT id,profile_id,purpose_id,destination,format,target,preview_fingerprint,manifest_json,omitted_count,created_at FROM context_exports ORDER BY created_at DESC").all() }); return true; }
  if (request.method === "GET" && parts[0] === "v1" && parts[1] === "context-exports" && parts[2]) { const item = db.prepare("SELECT * FROM context_exports WHERE id=?").get(parts[2]); send(response, item ? 200 : 404, item ? { item } : { error: "export_not_found" }); return true; }
  if (request.method === "POST" && url.pathname === "/v1/privacy/safe-delete/plan") { const input = await body(request); const entryId = text(input.entryId); const entry = db.prepare("SELECT template_id FROM context_entries WHERE id=? AND status!='archived'").get(entryId) as { template_id: string } | undefined; if (!entry) { send(response, 404, { error: "entry_not_found" }); return true; } const values = Number((db.prepare("SELECT COUNT(*) AS count FROM context_values WHERE entry_id=?").get(entryId) as any).count); const revisions = Number((db.prepare("SELECT COUNT(*) AS count FROM context_value_revisions WHERE entry_id=?").get(entryId) as any).count); const candidates = Number((db.prepare("SELECT COUNT(*) AS count FROM context_entry_candidates WHERE entry_id=?").get(entryId) as any).count); const exports = Number((db.prepare("SELECT COUNT(*) AS count FROM context_exports WHERE profile_id IN (SELECT profile_id FROM context_profile_fields WHERE template_id=? AND field_key IN (SELECT field_key FROM context_values WHERE entry_id=?))").get(entry.template_id, entryId) as any).count); const planId = newId("delete_plan"), confirmation = `DELETE ${planId}`, summary = { values, revisions, candidates, exports }; db.prepare("INSERT INTO privacy_safe_delete_plans(id,entry_id,confirmation_token,summary_json,status,created_at) VALUES(?,?,?,?,?,?)").run(planId, entryId, confirmation, JSON.stringify(summary), "planned", now()); audit("plan_safe_delete", { entryId, planId, ...summary }); send(response, 200, { planId, entryId, confirmation, summary, irreversible: true }); return true; }
  if (request.method === "POST" && url.pathname === "/v1/privacy/safe-delete/execute") { const input = await body(request); const planId = text(input.planId), entryId = text(input.entryId); const plan = db.prepare("SELECT * FROM privacy_safe_delete_plans WHERE id=? AND entry_id=? AND status='planned'").get(planId, entryId) as any; if (!plan || text(input.confirmation) !== plan.confirmation_token) { send(response, 400, { error: "safe_delete_confirmation_required" }); return true; } const entry = db.prepare("SELECT template_id FROM context_entries WHERE id=?").get(entryId) as { template_id: string } | undefined; if (!entry) { send(response, 404, { error: "entry_not_found" }); return true; } db.exec("BEGIN IMMEDIATE"); try { db.prepare("DELETE FROM context_exports WHERE profile_id IN (SELECT profile_id FROM context_profile_fields WHERE template_id=? AND field_key IN (SELECT field_key FROM context_values WHERE entry_id=?))").run(entry.template_id, entryId); db.prepare("DELETE FROM context_entries WHERE id=?").run(entryId); db.prepare("UPDATE privacy_safe_delete_plans SET status='executed',executed_at=? WHERE id=?").run(now(), planId); audit("safe_delete_entry", { entryId, planId }); db.exec("COMMIT"); } catch (error) { db.exec("ROLLBACK"); throw error; } send(response, 200, { deleted: true, entryId }); return true; }
  return false;
}
