import type { IncomingMessage, ServerResponse } from "node:http";
import { copyFileSync, mkdirSync, readFileSync, renameSync, statSync, unlinkSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type { DatabaseSync } from "node:sqlite";
import { decryptFileBytes, encryptFileBytes, encryptionFingerprint } from "../../../../packages/crypto/src/index.ts";
import { readBackupRecords, readOperationsStatus } from "../services/operations.ts";

type OperationsContext = { db: DatabaseSync; databasePath: string; backupDirectory: string; watcherStatePath: string; encryptionKey?: Buffer; send: (response: ServerResponse, status: number, value: unknown) => unknown; now: () => string; newId: (prefix: string) => string; fileHash: (path: string) => string; audit: (action: string, summary: unknown) => void; provenance: (input: any) => void };

export async function handleOperationsRoute(request: IncomingMessage, response: ServerResponse, url: URL, parts: string[], context: OperationsContext): Promise<boolean> {
  const { db, send } = context;
  if (request.method === "GET" && url.pathname === "/v1/ops/status") { send(response, 200, readOperationsStatus({ db, watcherStatePath: context.watcherStatePath, databasePath: context.databasePath, encryptionConfigured: Boolean(context.encryptionKey) })); return true; }
  if (request.method === "GET" && url.pathname === "/v1/dashboard/audit") { const limit = Math.min(Math.max(Number(url.searchParams.get("limit") ?? 100) || 100, 1), 100); const action = text(url.searchParams.get("action")); const cursorParts = text(url.searchParams.get("before")).split("|"); const beforeAt = cursorParts.length > 1 ? cursorParts[0] : ""; const beforeId = cursorParts.length > 1 ? cursorParts.slice(1).join("|") : ""; const predicate = beforeAt && beforeId ? " AND (created_at < ? OR (created_at = ? AND id < ?))" : ""; const params = predicate ? [beforeAt, beforeAt, beforeId] : []; const query = (base: string) => action ? db.prepare(`${base} AND action=?${predicate} ORDER BY created_at DESC, id DESC LIMIT ?`).all(action, ...params, limit) : db.prepare(`${base}${predicate} ORDER BY created_at DESC, id DESC LIMIT ?`).all(...params, limit); const items = query("SELECT id,action,summary_json,created_at FROM privacy_audit_logs WHERE 1=1"); const last = items.at(-1) as { id?: string; created_at?: string } | undefined; send(response, 200, { items, nextCursor: items.length === limit && last?.id && last.created_at ? `${last.created_at}|${last.id}` : null }); return true; }
  if (request.method === "GET" && url.pathname === "/v1/backups") { send(response, 200, { items: readBackupRecords(db, context.backupDirectory, context.fileHash) }); return true; }
  if (request.method === "POST" && url.pathname === "/v1/backups") { mkdirSync(context.backupDirectory, { recursive: true }); const id = context.newId("backup"), encrypted = Boolean(context.encryptionKey), fileName = `${id}.${encrypted ? "sqlite3.enc" : "sqlite3"}`, plainPath = resolve(context.backupDirectory, `${id}.sqlite3`), filePath = resolve(context.backupDirectory, fileName); db.exec(`VACUUM INTO '${plainPath.replaceAll("'", "''")}'`); if (encrypted) { writeFileSync(filePath, encryptFileBytes(readFileSync(plainPath), context.encryptionKey)); unlinkSync(plainPath); } else if (filePath !== plainPath) copyFileSync(plainPath, filePath); const timestamp = context.now(), size = statSync(filePath).size, hash = context.fileHash(filePath); db.prepare("INSERT INTO context_backups(id,file_name,file_size,file_hash,encrypted,created_at,verified_at) VALUES(?,?,?,?,?,?,?)").run(id, fileName, size, hash, encrypted ? 1 : 0, timestamp, timestamp); context.audit("create_backup", { backupId: id, fileSize: size, encrypted }); context.provenance({ subjectType: "backup", subjectId: id, eventType: "created", actorType: "system", sourceRef: fileName, sourceContentHash: hash, metadata: { fileSize: size, encrypted } }); send(response, 201, { id, fileName, fileSize: size, fileHash: hash, encrypted, encryptionKeyFingerprint: encryptionFingerprint(context.encryptionKey), createdAt: timestamp }); return true; }
  if (request.method === "POST" && parts[0] === "v1" && parts[1] === "backups" && parts[2] && parts[3] === "restore-plan") { const backup = db.prepare("SELECT * FROM context_backups WHERE id=?").get(parts[2]) as any; if (!backup) { send(response, 404, { error: "backup_not_found" }); return true; } const filePath = resolve(context.backupDirectory, backup.file_name); if (context.fileHash(filePath) !== backup.file_hash) { send(response, 409, { error: "backup_integrity_failed" }); return true; } const id = context.newId("restore_plan"), confirmation = `RESTORE ${parts[2]}`; db.prepare("INSERT INTO context_restore_plans(id,backup_id,confirmation_token,status,created_at) VALUES(?,?,?,?,?)").run(id, parts[2], confirmation, "planned", context.now()); send(response, 200, { planId: id, backupId: parts[2], confirmation, restartRequired: true }); return true; }
  if (request.method === "POST" && parts[0] === "v1" && parts[1] === "backups" && parts[2] && parts[3] === "restore") { const input = await readBody(request); const plan = db.prepare("SELECT p.*,b.file_name,b.file_hash,b.encrypted FROM context_restore_plans p JOIN context_backups b ON b.id=p.backup_id WHERE p.id=? AND p.backup_id=? AND p.status='planned'").get(text(input.planId), parts[2]) as any; if (!plan || text(input.confirmation) !== plan.confirmation_token) { send(response, 400, { error: "restore_confirmation_required" }); return true; } const filePath = resolve(context.backupDirectory, plan.file_name); if (context.fileHash(filePath) !== plan.file_hash) { send(response, 409, { error: "backup_integrity_failed" }); return true; } const stagingPath = `${context.databasePath}.restore`; if (plan.encrypted) writeFileSync(stagingPath, decryptFileBytes(readFileSync(filePath), context.encryptionKey)); else copyFileSync(filePath, stagingPath); db.prepare("UPDATE context_restore_plans SET status='executed',executed_at=? WHERE id=?").run(context.now(), plan.id); context.audit("restore_backup_scheduled", { backupId: parts[2], planId: plan.id, encrypted: Boolean(plan.encrypted) }); send(response, 202, { restoring: true, restartRequired: true }); setTimeout(() => { try { db.close(); renameSync(context.databasePath, `${context.databasePath}.before-restore`); renameSync(stagingPath, context.databasePath); process.exit(0); } catch (error) { console.error(`Restore failed: ${error instanceof Error ? error.message : String(error)}`); process.exit(1); } }, 100); return true; }
  return false;
}

function text(value: unknown) { return typeof value === "string" ? value.trim() : ""; }
async function readBody(request: IncomingMessage): Promise<Record<string, unknown>> { const chunks: Buffer[] = []; for await (const chunk of request) chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)); const value = JSON.parse(Buffer.concat(chunks).toString("utf8") || "{}"); return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
