import type { IncomingMessage, ServerResponse } from "node:http";
import type { DatabaseSync } from "node:sqlite";

export type ProfileRouteContext = { db: DatabaseSync; send: (response: ServerResponse, status: number, value: unknown) => unknown; body: (request: IncomingMessage) => Promise<Record<string, unknown>>; text: (value: unknown) => string; now: () => string; newId: (prefix: string) => string; audit: (action: string, summary: unknown) => void; validPurpose: (id: string) => boolean; };

export async function handleProfileRoute(request: IncomingMessage, response: ServerResponse, url: URL, parts: string[], context: ProfileRouteContext): Promise<boolean> {
  const { db, send, body, text, now, newId, audit, validPurpose } = context;
  if (request.method === "GET" && url.pathname === "/v1/context-profiles") { send(response, 200, { items: db.prepare("SELECT * FROM context_profiles WHERE is_active=1 ORDER BY updated_at DESC").all() }); return true; }
  if (request.method === "GET" && parts[0] === "v1" && parts[1] === "context-profiles" && parts[2]) { const item = db.prepare("SELECT * FROM context_profiles WHERE id=? AND is_active=1").get(parts[2]) as any; if (!item) { send(response, 404, { error: "profile_not_found" }); return true; } const fields = db.prepare("SELECT template_id,field_key FROM context_profile_fields WHERE profile_id=? ORDER BY template_id,field_key").all(parts[2]); send(response, 200, { item, fields }); return true; }
  if (request.method === "POST" && url.pathname === "/v1/context-profiles") { const input = await body(request); const selected = Array.isArray(input.includedFields) ? input.includedFields as Array<{ templateId: string; fieldKey: string }> : []; const purposeId = text(input.purposeId); const target = text(input.target) || "generic_ai_prompt"; const detailLevel = text(input.detailLevel) || "standard"; const includeMachineMeasured = input.includeMachineMeasured === true; const maximumCharacters = input.maximumCharacters === undefined || input.maximumCharacters === null || input.maximumCharacters === "" ? null : Number(input.maximumCharacters); const maximumTokens = input.maximumTokens === undefined || input.maximumTokens === null || input.maximumTokens === "" ? null : Number(input.maximumTokens); if (!text(input.name) || !selected.length || (purposeId && !validPurpose(purposeId)) || !["short", "standard", "detailed"].includes(detailLevel) || (maximumCharacters !== null && (!Number.isInteger(maximumCharacters) || maximumCharacters < 100)) || (maximumTokens !== null && (!Number.isInteger(maximumTokens) || maximumTokens < 25))) { send(response, 400, { error: "profile_invalid" }); return true; } for (const item of selected) if (!db.prepare("SELECT 1 FROM context_template_fields WHERE template_id=? AND field_key=?").get(item.templateId, item.fieldKey)) { send(response, 400, { error: "profile_field_not_found" }); return true; } const id = newId("profile"), createdAt = now(); db.exec("BEGIN IMMEDIATE"); try { db.prepare("INSERT INTO context_profiles(id,name,target,purpose_id,detail_level,maximum_characters,maximum_tokens,include_machine_measured,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)").run(id, text(input.name), target, purposeId || null, detailLevel, maximumCharacters, maximumTokens, includeMachineMeasured ? 1 : 0, createdAt, createdAt); const insert = db.prepare("INSERT INTO context_profile_fields(profile_id,template_id,field_key) VALUES(?,?,?)"); for (const item of selected) insert.run(id, item.templateId, item.fieldKey); db.exec("COMMIT"); } catch (error) { db.exec("ROLLBACK"); throw error; } audit("create_context_profile", { profileId: id, target, fieldCount: selected.length, includeMachineMeasured }); send(response, 201, { id, target, maximumCharacters, maximumTokens, includeMachineMeasured }); return true; }
  if (request.method === "PUT" && parts[0] === "v1" && parts[1] === "context-profiles" && parts[2]) { const input = await body(request); const name = text(input.name); const target = text(input.target); const purposeId = text(input.purposeId); const detailLevel = text(input.detailLevel) || "standard"; const includeMachineMeasured = input.includeMachineMeasured === true; const selected = Array.isArray(input.includedFields) ? input.includedFields as Array<{ templateId: string; fieldKey: string }> : []; const maximumCharacters = input.maximumCharacters === undefined || input.maximumCharacters === null || input.maximumCharacters === "" ? null : Number(input.maximumCharacters); const maximumTokens = input.maximumTokens === undefined || input.maximumTokens === null || input.maximumTokens === "" ? null : Number(input.maximumTokens); if (!name || !target || !selected.length || (purposeId && !validPurpose(purposeId)) || !["short", "standard", "detailed"].includes(detailLevel) || (maximumCharacters !== null && (!Number.isInteger(maximumCharacters) || maximumCharacters < 100)) || (maximumTokens !== null && (!Number.isInteger(maximumTokens) || maximumTokens < 25))) { send(response, 400, { error: "profile_invalid" }); return true; } for (const item of selected) if (!db.prepare("SELECT 1 FROM context_template_fields WHERE template_id=? AND field_key=?").get(item.templateId, item.fieldKey)) { send(response, 400, { error: "profile_field_not_found" }); return true; } if (!db.prepare("SELECT id FROM context_profiles WHERE id=? AND is_active=1").get(parts[2])) { send(response, 404, { error: "profile_not_found" }); return true; } db.exec("BEGIN IMMEDIATE"); try { db.prepare("UPDATE context_profiles SET name=?,target=?,purpose_id=?,detail_level=?,maximum_characters=?,maximum_tokens=?,include_machine_measured=?,updated_at=? WHERE id=? AND is_active=1").run(name, target, purposeId || null, detailLevel, maximumCharacters, maximumTokens, includeMachineMeasured ? 1 : 0, now(), parts[2]); db.prepare("DELETE FROM context_profile_fields WHERE profile_id=?").run(parts[2]); const insert = db.prepare("INSERT INTO context_profile_fields(profile_id,template_id,field_key) VALUES(?,?,?)"); for (const item of selected) insert.run(parts[2], item.templateId, item.fieldKey); db.exec("COMMIT"); } catch (error) { db.exec("ROLLBACK"); throw error; } audit("update_context_profile", { profileId: parts[2], fieldCount: selected.length, includeMachineMeasured }); send(response, 200, { updated: true }); return true; }
  if (request.method === "POST" && parts.join("/").match(/^v1\/context-profiles\/[^/]+\/archive$/)) { const result = db.prepare("UPDATE context_profiles SET is_active=0,updated_at=? WHERE id=? AND is_active=1").run(now(), parts[2]); if (!result.changes) { send(response, 404, { error: "profile_not_found" }); return true; } audit("archive_context_profile", { profileId: parts[2] }); send(response, 200, { archived: true }); return true; }
  return false;
}
