import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { DatabaseSync } from "node:sqlite";
import { existsSync, mkdirSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { eligibleForExport, formatExport, isSecretLike, newId, validateCandidate, validateField, type ContextTemplateField, type Sharing, type Sensitivity } from "../../../packages/domain/src/index.ts";

const root = resolve(import.meta.dirname, "../../..");
const databasePath = process.env.PCS_DB ?? resolve(root, "data", "personal-context-studio.sqlite3");
mkdirSync(dirname(databasePath), { recursive: true });
const db = new DatabaseSync(databasePath);
db.exec(readFileSync(resolve(root, "db", "schema.sql"), "utf8"));
const now = () => new Date().toISOString();
const allowedSharing = new Set<Sharing>(["always", "purpose_only", "private", "never"]);
const allowedSensitivity = new Set<Sensitivity>(["normal", "sensitive", "highly_sensitive"]);

function send(response: ServerResponse, status: number, value: unknown) { response.writeHead(status, { "content-type": "application/json; charset=utf-8" }); response.end(JSON.stringify(value)); }
async function body(request: IncomingMessage): Promise<Record<string, unknown>> { const chunks: Buffer[] = []; for await (const chunk of request) chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)); try { const value = JSON.parse(Buffer.concat(chunks).toString("utf8") || "{}"); return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; } catch { throw new Error("invalid_json"); } }
function text(value: unknown) { return typeof value === "string" ? value.trim() : ""; }
function fields(templateId: string) { return db.prepare("SELECT * FROM context_template_fields WHERE template_id=? ORDER BY display_order").all(templateId).map((field: any) => ({ ...field, required: Boolean(field.required), options: JSON.parse(field.options_json) })); }
function templateDetail(id: string) { const template = db.prepare("SELECT * FROM context_templates WHERE id=?").get(id) as any; return template ? { ...template, fields: fields(id) } : undefined; }
function audit(action: string, summary: unknown) { db.prepare("INSERT INTO privacy_audit_logs(id,action,summary_json,created_at) VALUES(?,?,?,?)").run(newId("audit"), action, JSON.stringify(summary), now()); }
function exportPreview(profileId: string, format: "markdown" | "json" | "agents" | "chatgpt") {
  const profile = db.prepare("SELECT * FROM context_profiles WHERE id=?").get(profileId) as any;
  if (!profile) throw new Error("profile_not_found");
  const selected = db.prepare("SELECT template_id,field_key FROM context_profile_fields WHERE profile_id=?").all(profileId) as Array<{ template_id: string; field_key: string }>;
  const placeholders = selected.length ? selected.map(() => "?").join(",") : "''";
  const rows = db.prepare(`SELECT v.*,f.label,e.template_id FROM context_values v JOIN context_entries e ON e.id=v.entry_id JOIN context_template_fields f ON f.template_id=e.template_id AND f.field_key=v.field_key WHERE e.status='active' AND (e.template_id || ':' || v.field_key) IN (${placeholders}) ORDER BY v.updated_at DESC`).all(...selected.map((item) => `${item.template_id}:${item.field_key}`)) as any[];
  const latest = new Map<string, any>(); for (const row of rows) if (!latest.has(`${row.template_id}:${row.field_key}`)) latest.set(`${row.template_id}:${row.field_key}`, row);
  const safe = [...latest.values()].filter((row) => eligibleForExport({ sharing: row.sharing, sensitivity: row.sensitivity, userConfirmed: Boolean(row.user_confirmed) }));
  const content = formatExport(safe.map((row) => ({ label: row.label, value: JSON.parse(row.value_json) })), format);
  const maximum = typeof profile.maximum_characters === "number" ? profile.maximum_characters : 12000;
  return { content: content.slice(0, maximum), omittedCount: latest.size - safe.length + (content.length > maximum ? 1 : 0), profile };
}

const server = createServer(async (request, response) => {
  try {
    const url = new URL(request.url ?? "/", "http://127.0.0.1");
    const parts = url.pathname.split("/").filter(Boolean);
    if (request.method === "GET" && url.pathname === "/health") return send(response, 200, { ok: true, service: "personal-context-studio" });
    if (request.method === "GET" && url.pathname === "/") { response.writeHead(200, { "content-type": "text/html; charset=utf-8" }); return response.end("<!doctype html><title>Personal Context Studio</title><main><h1>Personal Context Studio</h1><p>Local-first personal context for AI sharing.</p><p>Use the local API or CLI to create templates, entries, profiles, imports, and exports.</p></main>"); }
    if (request.method === "GET" && url.pathname === "/v1/context-templates") return send(response, 200, { items: db.prepare("SELECT * FROM context_templates WHERE status!='archived' ORDER BY updated_at DESC").all() });
    if (request.method === "POST" && url.pathname === "/v1/context-templates") {
      const input = await body(request); const name = text(input.name); const purpose = text(input.purpose) || "custom"; const rawFields = Array.isArray(input.fields) ? input.fields as ContextTemplateField[] : [];
      if (!name || !rawFields.length) return send(response, 400, { error: "template_invalid" });
      const validated = rawFields.map(validateField); const orders = new Set(validated.map((field) => field.displayOrder)); if (orders.size !== validated.length) return send(response, 400, { error: "template_field_order_invalid" });
      const id = newId("template"), createdAt = now(); db.exec("BEGIN IMMEDIATE"); try { db.prepare("INSERT INTO context_templates(id,name,description,purpose,status,version,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)").run(id, name, text(input.description), purpose, "draft", 1, createdAt, createdAt); const insert = db.prepare("INSERT INTO context_template_fields(id,template_id,field_key,label,description,value_type,required,display_order,options_json,sharing_default,sensitivity,reason) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)"); for (const field of validated) insert.run(newId("field"), id, field.fieldKey, field.label, field.description ?? "", field.valueType, field.required ? 1 : 0, field.displayOrder, JSON.stringify(field.options ?? []), field.sharingDefault, field.sensitivity, field.reason); db.exec("COMMIT"); } catch (error) { db.exec("ROLLBACK"); throw error; }
      return send(response, 201, { item: templateDetail(id) });
    }
    if (request.method === "GET" && parts[0] === "v1" && parts[1] === "context-templates" && parts[2]) { const item = templateDetail(parts[2]); return item ? send(response, 200, { item }) : send(response, 404, { error: "template_not_found" }); }
    if (request.method === "POST" && parts.join("/").match(/^v1\/context-templates\/[^/]+\/activate$/)) { const updated = db.prepare("UPDATE context_templates SET status='active',updated_at=? WHERE id=? AND status='draft'").run(now(), parts[2]); return updated.changes ? send(response, 200, { activated: true }) : send(response, 404, { error: "template_not_found_or_not_draft" }); }
    if (request.method === "GET" && url.pathname === "/v1/context-entries") return send(response, 200, { items: db.prepare("SELECT * FROM context_entries WHERE status!='archived' ORDER BY updated_at DESC").all() });
    if (request.method === "POST" && url.pathname === "/v1/context-entries") {
      const input = await body(request); const template = templateDetail(text(input.templateId)); const values = input.values && typeof input.values === "object" ? input.values as Record<string, unknown> : null; if (!template || !values) return send(response, 400, { error: "entry_invalid" });
      const id = newId("entry"), createdAt = now(); db.exec("BEGIN IMMEDIATE"); try { db.prepare("INSERT INTO context_entries(id,template_id,template_version,status,created_at,updated_at) VALUES(?,?,?,?,?,?)").run(id, template.id, template.version, "draft", createdAt, createdAt); const insert = db.prepare("INSERT INTO context_values(id,entry_id,field_key,value_json,source,source_id,user_confirmed,sharing,sensitivity,recorded_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)"); for (const field of template.fields) { const value = values[field.field_key]; if (field.required && (value === undefined || value === null || value === "")) throw new Error("required_context_value_missing"); if (value === undefined) continue; if (isSecretLike(value)) throw new Error("secret_value_prohibited"); const sharing = allowedSharing.has(text((input.sharing as any)?.[field.field_key]) as Sharing) ? (input.sharing as any)[field.field_key] : field.sharing_default; const sensitivity = allowedSensitivity.has(text((input.sensitivity as any)?.[field.field_key]) as Sensitivity) ? (input.sensitivity as any)[field.field_key] : field.sensitivity; insert.run(newId("value"), id, field.field_key, JSON.stringify(value), "user_input", null, 1, sharing, sensitivity, createdAt, createdAt); } db.prepare("UPDATE context_entries SET status='active',updated_at=? WHERE id=?").run(createdAt, id); db.exec("COMMIT"); } catch (error) { db.exec("ROLLBACK"); throw error; } return send(response, 201, { id });
    }
    if (request.method === "PATCH" && parts[0] === "v1" && parts[1] === "context-entries" && parts[2]) { const input = await body(request); const fieldKey = text(input.fieldKey); if (!fieldKey || isSecretLike(input.value)) return send(response, 400, { error: "context_value_invalid" }); const result = db.prepare("UPDATE context_values SET value_json=?,user_confirmed=1,updated_at=? WHERE entry_id=? AND field_key=?").run(JSON.stringify(input.value), now(), parts[2], fieldKey); return result.changes ? send(response, 200, { updated: true }) : send(response, 404, { error: "context_value_not_found" }); }
    if (request.method === "DELETE" && parts[0] === "v1" && parts[1] === "context-entries" && parts[2]) { db.prepare("UPDATE context_entries SET status='archived',updated_at=? WHERE id=?").run(now(), parts[2]); audit("archive_entry", { entryId: parts[2] }); return send(response, 200, { archived: true }); }
    if (request.method === "GET" && url.pathname === "/v1/context-profiles") return send(response, 200, { items: db.prepare("SELECT * FROM context_profiles ORDER BY updated_at DESC").all() });
    if (request.method === "POST" && url.pathname === "/v1/context-profiles") { const input = await body(request); const selected = Array.isArray(input.includedFields) ? input.includedFields as Array<{ templateId: string; fieldKey: string }> : []; if (!text(input.name) || !selected.length) return send(response, 400, { error: "profile_invalid" }); const id = newId("profile"), createdAt = now(); db.exec("BEGIN IMMEDIATE"); try { db.prepare("INSERT INTO context_profiles(id,name,target,detail_level,maximum_characters,created_at,updated_at) VALUES(?,?,?,?,?,?,?)").run(id, text(input.name), text(input.target) || "generic", text(input.detailLevel) || "standard", typeof input.maximumCharacters === "number" ? input.maximumCharacters : null, createdAt, createdAt); const insert = db.prepare("INSERT INTO context_profile_fields(profile_id,template_id,field_key) VALUES(?,?,?)"); for (const item of selected) insert.run(id, item.templateId, item.fieldKey); db.exec("COMMIT"); } catch (error) { db.exec("ROLLBACK"); throw error; } return send(response, 201, { id }); }
    if (request.method === "POST" && url.pathname === "/v1/context-imports/metheory") { const input = await body(request); const candidate = validateCandidate(input); const existing = db.prepare("SELECT id FROM context_import_records WHERE source_system='metheory' AND source_candidate_id=?").get(candidate.id) as any; if (existing) return send(response, 200, { id: existing.id, duplicate: true }); const id = newId("import"), createdAt = now(); db.prepare("INSERT INTO context_import_records(id,source_system,source_candidate_id,source_hypothesis_id,payload_json,decision,imported_at) VALUES(?,?,?,?,?,?,?)").run(id, "metheory", candidate.id, candidate.sourceHypothesisId, JSON.stringify(candidate), "pending", createdAt); audit("import_mettheory_candidate", { importId: id, sourceCandidateId: candidate.id }); return send(response, 201, { id, decision: "pending" }); }
    if (request.method === "GET" && url.pathname === "/v1/context-imports") return send(response, 200, { items: db.prepare("SELECT * FROM context_import_records ORDER BY imported_at DESC").all() });
    if (request.method === "POST" && parts.join("/").match(/^v1\/context-imports\/[^/]+\/decision$/)) { const input = await body(request); const decision = text(input.decision); if (!["accepted","edited_and_accepted","held","rejected"].includes(decision)) return send(response, 400, { error: "import_decision_invalid" }); const result = db.prepare("UPDATE context_import_records SET decision=?,target_template_id=?,target_field_key=? WHERE id=?").run(decision, text(input.templateId) || null, text(input.fieldKey) || null, parts[2]); audit("decide_import", { importId: parts[2], decision }); return result.changes ? send(response, 200, { decision }) : send(response, 404, { error: "import_not_found" }); }
    if (request.method === "POST" && (url.pathname === "/v1/context-exports/preview" || url.pathname === "/v1/context-exports")) { const input = await body(request); const format = text(input.format) as "markdown" | "json" | "agents" | "chatgpt"; if (!["markdown","json","agents","chatgpt"].includes(format)) return send(response, 400, { error: "export_format_invalid" }); const preview = exportPreview(text(input.profileId), format); if (url.pathname.endsWith("preview")) return send(response, 200, preview); const id = newId("export"); db.prepare("INSERT INTO context_exports(id,profile_id,format,content,omitted_count,created_at) VALUES(?,?,?,?,?,?)").run(id, preview.profile.id, format, preview.content, preview.omittedCount, now()); audit("export_context", { exportId: id, format, omittedCount: preview.omittedCount }); return send(response, 201, { id, ...preview }); }
    if (request.method === "GET" && parts[0] === "v1" && parts[1] === "context-exports" && parts[2]) { const item = db.prepare("SELECT * FROM context_exports WHERE id=?").get(parts[2]); return item ? send(response, 200, { item }) : send(response, 404, { error: "export_not_found" }); }
    if (request.method === "POST" && url.pathname === "/v1/privacy/safe-delete/plan") { const input = await body(request); const entryId = text(input.entryId); if (!entryId || !db.prepare("SELECT id FROM context_entries WHERE id=?").get(entryId)) return send(response, 404, { error: "entry_not_found" }); const planId = newId("delete_plan"); return send(response, 200, { planId, entryId, confirmation: `DELETE ${planId}`, irreversible: true }); }
    if (request.method === "POST" && url.pathname === "/v1/privacy/safe-delete/execute") { const input = await body(request); const planId = text(input.planId), entryId = text(input.entryId); if (!planId || text(input.confirmation) !== `DELETE ${planId}`) return send(response, 400, { error: "safe_delete_confirmation_required" }); db.exec("BEGIN IMMEDIATE"); try { db.prepare("DELETE FROM context_entries WHERE id=?").run(entryId); audit("safe_delete_entry", { entryId, planId }); db.exec("COMMIT"); } catch (error) { db.exec("ROLLBACK"); throw error; } return send(response, 200, { deleted: true, entryId }); }
    return send(response, 404, { error: "not_found" });
  } catch (error) { return send(response, 400, { error: error instanceof Error ? error.message : "request_failed" }); }
});
const port = Number(process.env.PCS_PORT ?? 8300);
server.listen(port, "127.0.0.1", () => console.log(`Personal Context Studio listening on http://127.0.0.1:${port}`));
